import { ChatStep } from './types';

export const CHAT_STEPS: ChatStep[] = [
  // ========== 인사 ==========
  {
    id: 'intro',
    messages: [
      '안녕 👋 나는 someonetheone이야.',
      '내가 원하는 사람은 주변에서 소개받기도 힘들고, 어디서 만나야 할지도 모르겠고... 그런 거 고민이었지?',
      '여기선 네가 직접 찾을 필요 없어. 네 이상형을 말해주면 AI가 인스타, 오프라인, 커뮤니티 어디든 뒤져서 딱 맞는 사람을 대신 찾아줄 거야.',
      '난 네 성공적인 연애를 위해 존재하는 AI야. 마당발 친구한테 소개받는다고 생각하면 돼 ㅎㅎ',
      '그러려면 너에 대해 좀 알아야 하거든. 시작해볼까?',
    ],
    inputType: 'choice',
    choices: ['좋아, 시작하자!'],
    field: '_ready',
    delay: 700,
  },

  // ========== 내 정보 ==========
  {
    id: 'name',
    messages: ['좋아! 먼저 뭐라고 부르면 돼?'],
    inputType: 'text',
    placeholder: '이름 또는 닉네임',
    field: 'name',
  },
  {
    id: 'gender',
    messages: ['반가워 {name}! 성별은?'],
    inputType: 'choice',
    choices: ['남자', '여자'],
    field: 'gender',
  },
  {
    id: 'birthdate',
    messages: ['생년월일 알려줘. 사주도 보고 궁합도 볼 거야 ㅎㅎ'],
    inputType: 'date',
    field: 'birthdate',
    reactions: ['오 좋아, 이거 나중에 궁합 볼 때 꽤 중요하거든 ㅎㅎ'],
  },
  {
    id: 'height',
    messages: ['키는 어느 정도야?'],
    inputType: 'choice',
    choices: ['160 이하', '161~165', '166~170', '171~175', '176~180', '181~185', '186 이상'],
    field: 'height',
    reactions: ['👍 참고할게!'],
  },
  {
    id: 'job',
    messages: ['직업은 뭐야? 뭐 하는 사람인지 궁금하다'],
    inputType: 'text',
    placeholder: '예: 개발자, 대학생, 마케터...',
    field: 'job',
    reactions: ['오 멋있다! 이거 상대한테 은근 매력 포인트야. 자기 일에 열정 있는 사람 좋아하는 사람 진짜 많거든.'],
  },
  {
    id: 'mbti',
    messages: ['MBTI는? 모르면 모른다고 해도 돼!'],
    inputType: 'choice',
    choices: [
      'INTJ', 'INTP', 'ENTJ', 'ENTP',
      'INFJ', 'INFP', 'ENFJ', 'ENFP',
      'ISTJ', 'ISFJ', 'ESTJ', 'ESFJ',
      'ISTP', 'ISFP', 'ESTP', 'ESFP',
      '몰라',
    ],
    field: 'mbti',
    reactions: {
      '몰라': ['괜찮아, MBTI 없어도 매칭하는 데 문제없어!'],
      '_default': ['ㅋㅋ 요즘 MBTI 물어보는 거 국룰이잖아. 상대한테 대화 소재로 쓰기 딱 좋아.'],
    },
  },
  {
    id: 'hobby',
    messages: ['주말에 보통 뭐 해? 취미 같은 거'],
    inputType: 'text',
    placeholder: '예: 넷플릭스, 헬스, 카페, 게임...',
    field: 'hobby',
    reactions: ['취미가 같으면 첫 만남에서 할 말이 넘쳐나거든. 이거 매칭할 때 꽤 중요해!'],
  },
  {
    id: 'photo',
    messages: [
      '이제 외모 차례인데... 😏',
      '사진 하나만 올려줘. 상대방 매칭할 때 참고할게.',
      '얼굴 안 나와도 되고, 분위기 사진도 OK야. 나중에 올려도 돼!',
    ],
    inputType: 'photo',
    field: 'photo',
    delay: 500,
  },
  {
    id: 'charm',
    messages: [
      '좋아 {name}, 너의 매력 포인트가 뭐라고 생각해?',
      '겸손하지 마. 여기선 자기 자랑이 미덕이야 ㅋㅋ',
    ],
    inputType: 'textarea',
    placeholder: '예: 웃을 때 눈이 없어진대, 요리를 잘해, 대화가 재밌다고...',
    field: 'charm',
    delay: 400,
    reactions: ['이야 그거 진짜 좋은 매력이다. 상대한테 "나 이런 사람이야" 하고 자연스럽게 어필하면 확 꽂힐 듯 👀'],
  },

  // ========== 가치관 ==========
  {
    id: 'values_intro',
    messages: [
      '자, 여기서부터 좀 솔직해져야 해.',
      '연애에서 진짜 중요한 건 겉모습보다 가치관이거든.',
      '완벽한 매칭을 위해서 민감한 것도 좀 물어볼게. 우리끼리니까 솔직하게!',
    ],
    inputType: 'choice',
    choices: ['알겠어, 물어봐'],
    field: '_values_ok',
    delay: 500,
  },
  {
    id: 'values_love',
    messages: ['연애에서 중요하게 생각하는 거, 중요한 순서대로 골라봐! 다 골라도 돼 ㅎㅎ'],
    inputType: 'ranked-choice',
    choices: ['신뢰/믿음', '대화/소통', '스킨십/애정표현', '유머/재미', '존중/배려', '함께하는 시간'],
    field: 'values_love',
    reactions: ['좋아, 이게 너의 연애 우선순위구나. 상대한테 "나한텐 이게 제일 중요해"라고 솔직하게 말하면 오히려 진지하게 봐줄 거야.'],
  },
  {
    id: 'values_life',
    messages: ['인생에서 제일 중요한 가치는?'],
    inputType: 'choice',
    choices: ['가족', '커리어/성공', '자유/독립', '안정/평화', '성장/배움', '즐거움/경험'],
    field: 'values_life',
    reactions: {
      '가족': ['가족 중시하는 사람한테 끌리는 사람 진짜 많아. 따뜻한 이미지가 확 생기거든.'],
      '커리어/성공': ['목표 있는 사람한테 끌리는 사람 많아. 열정 있는 모습 자체가 매력이야.'],
      '자유/독립': ['서로 존중하면서 자기 시간 가지는 거, 요즘 연애에서 되게 중요하지.'],
      '안정/평화': ['같이 있으면 편안한 사람이 결국 오래 가거든. 이거 엄청 큰 장점이야.'],
      '성장/배움': ['같이 성장하는 연애 원하는 사람한테 넌 딱이겠다!'],
      '즐거움/경험': ['인생 재밌게 사는 사람 옆에 있고 싶어하는 사람 많아. 이거 큰 매력이야 ㅎㅎ'],
    },
  },
  {
    id: 'religion',
    messages: [
      '이건 좀 민감한 건데... 종교 있어?',
      '매칭할 때 종교 때문에 안 맞는 경우가 진짜 많아서 물어보는 거야.',
    ],
    inputType: 'choice',
    choices: ['무교', '기독교', '천주교', '불교', '기타', '말하고 싶지 않아'],
    field: 'religion',
    delay: 300,
    reactions: ['ㅇㅇ 알겠어, 매칭할 때 참고할게!'],
  },

  // ========== 이상형 ==========
  {
    id: 'ideal_intro',
    messages: [
      '좋아, 너에 대해 많이 알게 됐어 💜',
      '이제 어떤 사람을 찾아줄지 알려줘.',
      '이상형 시간이다!',
    ],
    inputType: 'choice',
    choices: ['가보자!'],
    field: '_ideal_ok',
    delay: 500,
  },
  {
    id: 'ideal_age',
    messages: ['선호하는 나이대는?'],
    inputType: 'choice',
    choices: ['나보다 어린', '동갑', '1~3살 많은', '4~7살 많은', '나이 상관없어'],
    field: 'ideal_age',
    reactions: {
      '나이 상관없어': ['넓게 보는구나! 그러면 매칭 범위가 훨씬 넓어져서 좋아.'],
      '_default': ['ㅇㅋ 취향 존중! 그 나이대로 집중해서 찾아볼게.'],
    },
  },
  {
    id: 'ideal_look',
    messages: [
      '외모 스타일은 어떤 게 좋아?',
      '솔직하게 말해도 돼. 여기 판단 없음 ㅎㅎ',
    ],
    inputType: 'choice',
    choices: ['귀여운 스타일', '시크/쿨한 스타일', '청순한 스타일', '섹시한 스타일', '자연스러운/편한 스타일', '운동하는 건강미'],
    field: 'ideal_look',
    delay: 300,
    reactions: ['오 취향 확실하네 ㅎㅎ 그 스타일로 찾아볼게!'],
  },
  {
    id: 'ideal_personality',
    messages: ['성격은 어떤 사람이 좋아?'],
    inputType: 'choice',
    choices: ['조용하고 다정한', '밝고 에너지 넘치는', '지적이고 깊은', '유머 있고 털털한', '감성적이고 섬세한', '리드 잘하는 카리스마'],
    field: 'ideal_personality',
    reactions: {
      '조용하고 다정한': ['둘이 조용히 같이 있어도 편한 그런 느낌이지? 알겠어.'],
      '밝고 에너지 넘치는': ['같이 있으면 기분 좋아지는 사람! 찾아볼게 ㅎㅎ'],
      '지적이고 깊은': ['대화가 깊은 사람이랑 있으면 시간 가는 줄 모르지.'],
      '유머 있고 털털한': ['웃기는 사람이 최고긴 하지 ㅋㅋ 유머 센스 있는 사람 찾아줄게.'],
      '감성적이고 섬세한': ['작은 것도 챙겨주는 스타일이지? 그런 사람 옆에 있으면 행복하지.'],
      '리드 잘하는 카리스마': ['끌려가는 연애 좋아하는구나 ㅎㅎ 알겠어!'],
    },
  },
  {
    id: 'ideal_job',
    messages: ['상대 직업은 선호하는 게 있어?'],
    inputType: 'text',
    placeholder: '예: 상관없어, 전문직, 안정적인 직장...',
    field: 'ideal_job',
    reactions: ['ㅇㅇ 참고할게!'],
  },
  {
    id: 'ideal_dealbreaker',
    messages: [
      '이건 중요해.',
      '절대 안 되는 거 있어? 이건 진짜 싫다, 하는 거.',
    ],
    inputType: 'textarea',
    placeholder: '예: 흡연, 잠수 타는 사람, 연락 느린 사람...',
    field: 'ideal_dealbreaker',
    delay: 300,
    reactions: ['확실히 알겠어. 이건 무조건 필터링할게. 지뢰는 밟기 전에 피하는 게 낫지 ㅎㅎ'],
  },
  {
    id: 'ideal_religion',
    messages: ['상대 종교는 상관있어?'],
    inputType: 'choice',
    choices: ['나랑 같은 종교', '무교였으면', '상관없어', '말하고 싶지 않아'],
    field: 'ideal_religion',
    reactions: ['ㅇㅇ 알겠어!'],
  },
  {
    id: 'ideal_free',
    messages: [
      '마지막으로, 이상형에 대해 자유롭게 말해봐.',
      '"이런 사람이면 바로 넘어감" 하는 거 있어?',
      '구체적일수록 AI가 찾기 쉬워!',
    ],
    inputType: 'textarea',
    placeholder: '예: 같이 넷플릭스 보면서 치킨 먹을 수 있는 사람, 눈이 예쁜 사람...',
    field: 'ideal_free',
    delay: 400,
    reactions: ['완전 구체적이야 좋아! 이 정도면 AI가 제대로 찾을 수 있겠다 🔥'],
  },

  // ========== 연락처 ==========
  {
    id: 'phone',
    messages: [
      '거의 다 왔어!',
      '매칭 결과를 알려줄 전화번호만 남겨줘.',
      '문자로 카드 도착 알림 보내줄게.',
    ],
    inputType: 'phone',
    placeholder: '01012345678',
    field: 'phone',
    delay: 400,
  },
  {
    id: 'done',
    messages: [
      '완벽해 {name}! 🔥',
      '이제 너한테 딱 맞는 사람을 찾으러 갈게.',
      '그 전에 상대방에게 보여줄 네 소개 카드를 확인해볼까?',
    ],
    inputType: 'choice',
    choices: ['내 카드 보기'],
    field: '_done',
    delay: 500,
  },
];
