/**
 * dev-only mock 케이스 데이터. URL `?case=a|b|c|empty` 로 활성화.
 * 백엔드 GET /casting/auth/me/dashboard 응답 스키마(DashboardResponse) 그대로 모방.
 * production 빌드에서는 page.tsx 가 dev 가드를 통과한 경우에만 import 한다.
 */

import type { DashboardOrder, DashboardResponse, Match } from './types';

const HOURS = 1000 * 60 * 60;
const DAYS = HOURS * 24;
const iso = (msAgo: number) => new Date(Date.now() - msAgo).toISOString();

const MOCK_USER = {
  user_uid: 'mock-uid',
  email: 'mock@example.com',
  phone: '01012345678',
  last_login_at: iso(2 * HOURS),
  created_at: iso(30 * DAYS),
};

const STARTER_ORDER: DashboardOrder = {
  order_id: 'order-mock-1',
  product_id: 'starter',
  product_name: '스타터 · 5명 만남',
  credits: 5,
  amount: 39900,
  status: 'paid',
  paid_at: iso(30 * DAYS),
  created_at: iso(30 * DAYS),
};

const CASE_A: DashboardResponse = {
  user: MOCK_USER,
  phone_verified: true,
  credits: { balance: 4, total_purchased: 5, total_used: 1, linked_guest_count: 1 },
  orders: [STARTER_ORDER],
  matches: [
    {
      report_uid: 'A-001',
      status: 'published',
      stage: 'contact_requested',
      partner_source: 'guest',
      score: 86,
      order_id: STARTER_ORDER.order_id,
      report_url: '/casting/reports/A-001',
      contact_requested_at: iso(6 * HOURS),
      mutual_match_at: null,
      outreach_status: null,
      created_at: iso(2 * DAYS),
      updated_at: iso(6 * HOURS),
      partner_nickname: '연주',
      partner_age: 28,
      partner_region: '서울 마포',
      partner_job: '브랜드 디자이너',
      partner_tagline: '주말마다 책방 가는 분',
      viewer_action: 'contact_request',
    } satisfies Match,
  ],
};

const CASE_B: DashboardResponse = {
  user: MOCK_USER,
  phone_verified: true,
  credits: { balance: 0, total_purchased: 5, total_used: 5, linked_guest_count: 1 },
  orders: [STARTER_ORDER],
  matches: [
    {
      report_uid: 'B-001',
      status: 'published',
      stage: 'connected',
      partner_source: 'guest',
      score: 92,
      order_id: STARTER_ORDER.order_id,
      report_url: '/casting/reports/B-001',
      contact_requested_at: iso(2 * DAYS),
      mutual_match_at: iso(6 * HOURS),
      outreach_status: null,
      created_at: iso(4 * DAYS),
      updated_at: iso(6 * HOURS),
      partner_nickname: '서윤',
      partner_age: 27,
      partner_region: '서울 용산',
      partner_job: '브랜드 디렉터',
      partner_tagline: '한 달에 한 번 여행 가는 분',
      viewer_action: 'contact_request',
    } satisfies Match,
    {
      report_uid: 'B-002',
      status: 'published',
      stage: 'contact_requested',
      partner_source: 'guest',
      score: 88,
      order_id: STARTER_ORDER.order_id,
      report_url: '/casting/reports/B-002',
      contact_requested_at: iso(12 * HOURS),
      mutual_match_at: null,
      outreach_status: null,
      created_at: iso(2 * DAYS),
      updated_at: iso(12 * HOURS),
      partner_nickname: '도현',
      partner_age: 31,
      partner_region: '서울 강남',
      partner_job: '백엔드 개발자',
      partner_tagline: '주말 클라이밍 가는 분',
      viewer_action: 'contact_request',
    } satisfies Match,
    {
      report_uid: 'B-003',
      status: 'published',
      stage: 'ready',
      partner_source: 'guest',
      score: 81,
      order_id: STARTER_ORDER.order_id,
      report_url: '/casting/reports/B-003',
      contact_requested_at: null,
      mutual_match_at: null,
      outreach_status: null,
      created_at: iso(8 * HOURS),
      updated_at: iso(8 * HOURS),
      partner_nickname: '민재',
      partner_age: 30,
      partner_region: '서울 종로',
      partner_job: '내과 의사',
      partner_tagline: '아침 러닝 좋아하는 분',
      viewer_action: 'none',
    } satisfies Match,
    {
      report_uid: 'B-004',
      status: 'published',
      stage: 'contact_requested',
      partner_source: 'instagram',
      score: 84,
      order_id: STARTER_ORDER.order_id,
      report_url: '/casting/reports/B-004',
      contact_requested_at: iso(1 * DAYS),
      mutual_match_at: null,
      outreach_status: 'contacted',
      created_at: iso(2 * DAYS),
      updated_at: iso(1 * DAYS),
      partner_nickname: '하늬',
      partner_age: 29,
      partner_job: '잡지 에디터',
      partner_tagline: '주말마다 에세이 쓰는 분',
      viewer_action: 'contact_request',
    } satisfies Match,
    {
      report_uid: 'B-005',
      status: 'published',
      stage: 'failed',
      partner_source: 'guest',
      score: 79,
      order_id: STARTER_ORDER.order_id,
      report_url: '/casting/reports/B-005',
      contact_requested_at: iso(3 * DAYS),
      mutual_match_at: null,
      outreach_status: null,
      created_at: iso(5 * DAYS),
      updated_at: iso(1 * DAYS),
      partner_nickname: '하늘',
      partner_age: 29,
      partner_region: '서울 성수',
      partner_job: '퍼포먼스 마케터',
      partner_tagline: '와인 모임 운영하는 분',
      viewer_action: 'contact_request',
      ended_at: iso(1 * DAYS),
    } satisfies Match,
  ],
};

const CASE_C: DashboardResponse = {
  user: MOCK_USER,
  phone_verified: true,
  credits: { balance: 0, total_purchased: 5, total_used: 5, linked_guest_count: 1 },
  orders: [STARTER_ORDER],
  matches: [
    {
      report_uid: 'C-001',
      status: 'published',
      stage: 'failed',
      partner_source: 'guest',
      score: 80,
      order_id: STARTER_ORDER.order_id,
      report_url: '/casting/reports/C-001',
      contact_requested_at: iso(4 * HOURS),
      mutual_match_at: null,
      outreach_status: null,
      created_at: iso(2 * DAYS),
      updated_at: iso(0.2 * HOURS),
      partner_nickname: '나은',
      partner_age: 30,
      partner_job: '회계사',
      partner_tagline: '주말마다 영화관 가는 분',
      viewer_action: 'contact_request',
      ended_at: iso(0.2 * HOURS),
    } satisfies Match,
    {
      report_uid: 'C-002',
      status: 'published',
      stage: 'failed',
      partner_source: 'guest',
      score: 78,
      order_id: STARTER_ORDER.order_id,
      report_url: '/casting/reports/C-002',
      contact_requested_at: iso(2 * DAYS),
      mutual_match_at: null,
      outreach_status: null,
      created_at: iso(3 * DAYS),
      updated_at: iso(1 * DAYS),
      partner_nickname: '수아',
      partner_age: 27,
      partner_region: '서울 마포',
      partner_job: '간호사',
      partner_tagline: '베이킹이 취미인 분',
      viewer_action: 'contact_request',
      ended_at: iso(1 * DAYS),
    } satisfies Match,
    {
      report_uid: 'C-003',
      status: 'published',
      stage: 'failed',
      partner_source: 'guest',
      score: 75,
      order_id: STARTER_ORDER.order_id,
      report_url: '/casting/reports/C-003',
      contact_requested_at: iso(3 * DAYS),
      mutual_match_at: null,
      outreach_status: null,
      created_at: iso(5 * DAYS),
      updated_at: iso(2 * DAYS),
      partner_nickname: '예린',
      partner_age: 28,
      partner_region: '서울 종로',
      partner_job: '중학교 교사',
      partner_tagline: '독서 모임 운영하는 분',
      viewer_action: 'contact_request',
      ended_at: iso(2 * DAYS),
    } satisfies Match,
    {
      report_uid: 'C-004',
      status: 'published',
      stage: 'failed',
      partner_source: 'guest',
      score: 73,
      order_id: STARTER_ORDER.order_id,
      report_url: '/casting/reports/C-004',
      contact_requested_at: iso(5 * DAYS),
      mutual_match_at: null,
      outreach_status: null,
      created_at: iso(6 * DAYS),
      updated_at: iso(3 * DAYS - 4 * HOURS),
      partner_nickname: '윤서',
      partner_age: 29,
      partner_region: '서울 강서',
      partner_job: '바리스타',
      partner_tagline: '주말 로스팅 취미인 분',
      viewer_action: 'contact_request',
      ended_at: iso(3 * DAYS - 4 * HOURS),
    } satisfies Match,
    {
      report_uid: 'C-005',
      status: 'published',
      stage: 'ready',
      partner_source: 'guest',
      score: 77,
      order_id: STARTER_ORDER.order_id,
      report_url: '/casting/reports/C-005',
      contact_requested_at: null,
      mutual_match_at: null,
      outreach_status: null,
      created_at: iso(4 * DAYS),
      updated_at: iso(4 * DAYS),
      partner_nickname: '소영',
      partner_age: 26,
      partner_job: '제품 디자이너',
      partner_tagline: '동물권 활동 하는 분',
      viewer_action: 'pass',
      ended_at: iso(2 * DAYS - 3 * HOURS),
    } satisfies Match,
  ],
};

const EMPTY_CASE: DashboardResponse = {
  user: MOCK_USER,
  phone_verified: true,
  credits: { balance: 5, total_purchased: 5, total_used: 0, linked_guest_count: 1 },
  orders: [STARTER_ORDER],
  matches: [],
};

export const CASES = {
  a: { label: 'A · 1장 진행중', data: CASE_A },
  b: { label: 'B · 5장 혼합', data: CASE_B },
  c: { label: 'C · 5장 종료', data: CASE_C },
  empty: { label: '빈 상태', data: EMPTY_CASE },
} as const;

export type MockCaseKey = keyof typeof CASES;

export const DEFAULT_MOCK_KEY: MockCaseKey = 'b';
